version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    environment:
      - NODE_ENV=development
